config/routes.rb
Rails.application.routes.draw do
  

    devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
      resources :welcomes
  root to: 'welcomes#index'
  get 'welcomes/index'

end

app/models/user.rb
class User
  include Mongoid::Document
  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time

  include Mongoid::Attributes::Dynamic
  devise :omniauthable, :omniauth_providers => [:facebook]
  def self.from_omniauth(auth)
     where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
     user.email = auth.info.email
     user.password = Devise.friendly_token[0,20]
    end
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""
  field :provider,           type: String, default: ""


  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
end

app/models/welcome.rb
class Welcome
  include Mongoid::Document
  field :greeting, type: String
end

app/controllers/Users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
     @user = User.from_omniauth(request.env["omniauth.auth"])
     sign_in_and_redirect @user      
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  before_action :set_welcome, only: [:show, :edit, :update, :destroy]

  # GET /welcomes
  # GET /welcomes.json
  def index
    @welcomes = Welcome.all
  end

  # GET /welcomes/1
  # GET /welcomes/1.json
  def show
  end

  # GET /welcomes/new
  def new
    @welcome = Welcome.new
  end

  # GET /welcomes/1/edit
  def edit
  end

  # POST /welcomes
  # POST /welcomes.json
  def create
    @welcome = Welcome.new(welcome_params)

    respond_to do |format|
      if @welcome.save
        format.html { redirect_to @welcome, notice: 'Welcome was successfully created.' }
        format.json { render :show, status: :created, location: @welcome }
      else
        format.html { render :new }
        format.json { render json: @welcome.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /welcomes/1
  # PATCH/PUT /welcomes/1.json
  def update
    respond_to do |format|
      if @welcome.update(welcome_params)
        format.html { redirect_to @welcome, notice: 'Welcome was successfully updated.' }
        format.json { render :show, status: :ok, location: @welcome }
      else
        format.html { render :edit }
        format.json { render json: @welcome.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /welcomes/1
  # DELETE /welcomes/1.json
  def destroy
    @welcome.destroy
    respond_to do |format|
      format.html { redirect_to welcomes_url, notice: 'Welcome was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_welcome
      @welcome = Welcome.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def welcome_params
      params.require(:welcome).permit(:greeting)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TlogA1241514</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
                                           
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <% if user_signed_in? %>
      <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to("Log In", new_user_session_path) %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/welcomes/_form.html.haml
= form_for @welcome do |f|
  - if @welcome.errors.any?
    #error_explanation
      %h2= "#{pluralize(@welcome.errors.count, "error")} prohibited this welcome from being saved:"
      %ul
        - @welcome.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :greeting
    = f.text_area :greeting
  .actions
    = f.submit 'Save'

app/views/welcomes/edit.html.haml
%h1 Editing welcome

= render 'form'

= link_to 'Show', @welcome
\|
= link_to 'Back', welcomes_path

app/views/welcomes/index.html.haml
%h1 Listing welcomes

%table
  %thead
    %tr
      %th Greeting
      %th
      %th
      %th

  %tbody
    - @welcomes.each do |welcome|
      %tr
        %td= welcome.greeting
        %td= link_to 'Show', welcome
        %td= link_to 'Edit', edit_welcome_path(welcome)
        %td= link_to 'Destroy', welcome, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Welcome', new_welcome_path

app/views/welcomes/new.html.haml
%h1 New welcome

= render 'form'

= link_to 'Back', welcomes_path

app/views/welcomes/show.html.haml
%p#notice= notice

%p
  %b Greeting:
  = @welcome.greeting

= link_to 'Edit', edit_welcome_path(@welcome)
\|
= link_to 'Back', welcomes_path